
const REGISTER = {
    REGISTER_USER_BEGIN: "REGISTER_USER_BEGIN",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_ERROR: "REGISTER_USER_ERROR"
}

const LOGIN = {
    LOGIN_USER_BEGIN: "LOGIN_USER_BEGIN",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_ERROR: "LOGIN_USER_ERROR"
}

export const CONSTANTS = {
    REGISTER,
    LOGIN
}